version: '2'

services:
  nginx:
    image: olymk2/nginx
    container_name: "nginx"
    restart: unless-stopped
    networks: 
      - external
    ports:
      - 443:443
    volumes:
      - sockets:/data/sockets
      - /var/www/letsencrypt/:/var/www/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/nginx/sites-enabled/:/etc/nginx/sites-enabled/

networks:
  external:
    driver: bridge

volumes:
  sockets:
    driver: local
