version: '2'

services:
  nginx:
    build: .
    container_name: "nginx"
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - sockets:/data/sockets
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/nginx/sites-enabled/:/etc/nginx/sites-enabled/

networks:
  internal:
    driver: bridge

volumes:
  sockets:
    driver: local
